### ISSUE TITLE
Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive

### ISSUE THREAD

**Issue by huggingpixels** [padarom/guacamole-common-js#7]
Non-passive event listeners are throwing warnings in Chrome Version 86.0.4240.111 (Official Build) (64-bit)

zone.js:1832 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
15:32:38.170 zone.js:1832 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
15:32:38.170 zone.js:1832 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
15:32:38.171 zone.js:1832 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

As I see from the related documentation the solution would be a simple syntax change on the event listeners.
Is there any particular reason (eg. browser support) why it had not been done?

**Comment by padarom** [comment]
This isn't the upstream guacamole source code, this is merely a wrapper for npm distribution. Please feel free to report this issue through the official channels:

> Please report any bugs encountered by opening a new issue in the JIRA system
hosted at:
>    
>     https://issues.apache.org/jira/browse/GUACAMOLE/
